classdef Word < replab.Str
% Describes a word in a free group, or an equivalence class in a finitely presented group
%
% In a free group, this word describes a product of the group generators and their inverses.
% By convention, the word is composed of a sequence of letters, stored as an integer row vector.
% The generators have indices $1, 2, ..., n$, while the indices $-1, -2, ..., -n$ describe the
% inverses of those generators.
%
% In a free group, the words are always written in their reduced form. Words can always be compared
% by their letters.
%
% In a finitely presented group, the word is a representative of the equivalence class generated by the
% group relations. However, words cannot be compared by their letters; rather, we look for a permutation
% realization of the finitely presented group and compare words by their permutation images.

    properties
        group % (`+replab.FPGroup`): Group this word is part of
        letters % (integer(1,\*)): Word contents
    end

    methods

        function self = Word(group, letters)
            self.group = group;
            self.letters = replab.Word.reduceLetters(letters);
        end

        function l = length(self)
        % Number of letters composing this word
        %
        % Returns:
        %   integer: Number of letters in this word
            l = length(self.letters);
        end

        function s = word2str(self)
        % Returns a string representation of this word
        %
        % That string can be parsed back by `.FPGroup.parse`.
        %
        % Example:
        %   >>> [F x y] = replab.FreeGroup.of('x', 'y');
        %   >>> w = x*y/x
        %     x y x^-1
        %   >>> s = w.word2str
        %     'x y x^-1'
        %   >>> w1 = F.word(s)
        %     x y x^-1
        %
        % Returns:
        %   charstring: String representing the word
            if self.length == 0
                s = '1';
                return
            end
            s = '';
            sep = '';
            i = 1;
            word = self.letters;
            names = self.group.names;
            while i <= length(word)
                e = sign(word(i)); % exponent
                l = abs(word(i));
                assert(e ~= 0);
                i = i + 1;
                while i <= length(word) && abs(word(i)) == l
                    e = e + sign(word(i));
                    i = i + 1;
                end
                if e ~= 0
                    s = [s sep names{l}];
                    sep = ' ';
                    if e ~= 1
                        s = [s '^' num2str(e)];
                    end
                end
            end
        end

        function s = headerStr(self)
            s = self.word2str;
        end

        function s = shortStr(self, maxColumns)
            s = self.word2str;
        end

        function s = longStr(self, maxRows, maxColumns)
            s = {self.word2str};
        end

        function l = ne(self, rhs)
        % Compares words using the underlying group
            l = ~(self == eq);
        end

        function l = eq(self, rhs)
        % Compares words using the underlying group
            l = false;
            if self.group.groupId ~= rhs.group.groupId
                return
            end
            l = self.group.eqv(self, rhs);
        end

        function z = mtimes(self, rhs)
        % Word multiplication
            assert(self.group.groupId == rhs.group.groupId, 'Must multiply words of the same group');
            z = replab.Word(self.group, self.composeLetters(self.letters, rhs.letters));
        end

        function z = inv(self)
        % Inverse
            z = replab.Word(self.group, self.inverseLetters(self.letters));
        end

        function z = mrdivide(self, rhs)
        % Word multiplication by inverse
            z = self * inv(rhs);
        end

        function z = mpower(self, n)
        % Word power
            z = self.group.composeN(self, n);
        end

        function g = computeImage(self, target, generatorImages)
        % Computes the image of this word using the given generator images
        %
        % Does not verify the validity of the implied homomorphism.
        %
        % Args:
        %   target (`.Group`): Target group
        %   generatorImages (cell(1,\*) of ``target`` elements): Images of the generators in the target group
        %
        % Returns:
        %   element of ``target``: Computed image
            letters = self.letters;
            g = target.identity;
            for i = 1:length(letters)
                l = letters(i);
                if l > 0
                    g = target.compose(g, generatorImages{l});
                else
                    g = target.composeWithInverse(g, generatorImages{-l});
                end
            end
        end

    end

    methods (Static)

        function z = inverseLetters(x)
        % Inverts the word described the given letters
        %
        % Args:
        %   x (integer(1,\*)): Letters
        %
        % Returns:
        %   integer(1,\*): Letters of the word inverse
            z = -fliplr(x);
        end

        function z = composeLetters(x, y)
        % Composes the two words described the given letters
        %
        % If both arguments are reduced, it guarantees that the result is reduced too.
        %
        % Args:
        %   x (integer(1,\*)): Letters of the left hand side word
        %   y (integer(1,\*)): Letters of the right hand side word
        %
        % Returns:
        %   integer(1,\*): Letters of the product
            xe = length(x);
            ys = 1;
            yn = length(y);
            while xe > 0 && ys <= yn && x(xe) == -y(ys)
                xe = xe - 1;
                ys = ys + 1;
            end
            z = [x(1:xe) y(ys:end)];
        end

        function x = reduceLetters(x)
        % Finds the reduced form of the word described the given letters
        %
        % It eliminates all products of the form ``[i -i]`` or ``[-i i]`` for the index ``i`` of a generator.
        %
        % Args:
        %   x (integer(1,\*)): Letters
        %
        % Returns:
        %   integer(1,\*): Letters of the reduced word
            i = find(x(1:end-1) == -x(2:end));
            if ~isempty(i)
                while i < length(x)
                    if x(i) == -x(i+1)
                        x = [x(1:i-1) x(i+2:end)];
                        if i > 1
                            i = i - 1;
                        end
                    else
                    i = i + 1;
                    end
                end
            end
        end

    end

end
