# action.yml
name: 'docker'
description: 'Launcher docker image'
inputs:
  commit: # git commit to checkout
    description: 'git hash'
    required: true
    default: 'master'
runs:
  using: 'docker'
  image: '../../docker/sphinx/Dockerfile'
  args:
   - ${{ inputs.commit }}

